language: node_js
node_js:
  - '4.2.6'

cache:
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - firefox -marionette &

services:
  - mongodb
