language: node_js

node_js:
  - '4.2.6'

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  firefox: '45.0'

cache:
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - firefox -marionette &

services:
  - mongodb
